<?php
/**
 * @var ErrorContext $errorContext
 */
use Simplon\Error\ErrorContext;

?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>An error occured</title>
    <style type="text/css">
        body
        {
            font-family: 'Courier', sans-serif;
            background: #F77;
            margin: 20px;
            font-size: 16px;
        }

        #content
        {
            width: 90%;
            margin: auto;
            background: #fff;
            padding: 10px 30px;
            border-radius: 4px;
        }

        h1
        {
            font-weight: normal;
            margin: 20px 0 5px;
        }

        h1 span
        {
            color: #c00;
        }

        #date
        {
            font-size: 16px;
            color: #777;
            margin: 0 0 30px;
        }

        strong
        {
            display: block;
            padding: 10px 20px;
            background: #efefef;
            text-transform: capitalize;
        }

        pre
        {
            font-family: 'Courier', sans-serif;
        }

        p,
        pre
        {
            margin: 0 0 20px;
            background: #fee;
            padding: 20px;
            color: #555;
            word-break: break-all;
        }
    </style>
</head>
<body>
<div id="content">
    <div style="text-align: center">
        <h1>
            <span><?php echo $errorContext->getHttpStatusCode() ?></span>&nbsp;<?php echo $errorContext->getMessage() ?>
        </h1>

        <div id="date">Date/Time: <?php echo (new DateTime())->format('c') ?></div>
    </div>

    <?php foreach ($errorContext->getData() as $k => $v): ?>
        <?php if (is_array($v)): ?>

            <div>
                <strong><?php echo $k ?></strong>
                <pre><?php echo stripslashes(json_encode($v, JSON_PRETTY_PRINT)) ?></pre>
            </div>

        <?php else: ?>

            <div>
                <strong><?php echo preg_match('/^\d+$/', $k) === 1 ? '&nbsp;' : $k ?></strong>

                <?php if (empty($v) && $v !== 0): ?>

                    <p>[EMPTY VALUE]</p>

                <?php else: ?>

                    <p><?php echo $v ?></p>

                <?php endif ?>
            </div>

        <?php endif ?>
    <?php endforeach ?>
</div>
</body>
</html>