<?php
/**
 * @var ErrorContext $errorContext
 */
use Simplon\Error\ErrorContext;

?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>An error occured</title>
    <style type="text/css">
        body
        {
            font-family: 'Courier', sans-serif;
            background: #F77;
            margin: 20px;
            font-size: 16px;
        }

        #content
        {
            width: 90%;
            margin: auto;
            background: #fff;
            padding: 20px 30px 10px;
            border-radius: 4px;
        }

        h1, h2
        {
            margin: 0;
            font-weight: normal;
        }

        h1
        {
            font-size: 100px;
            line-height: 1em;
        }

        h1 span
        {
            color: #c00;
        }

        h2
        {
            padding: 10px 0 30px;
        }

        #date
        {
            font-size: 16px;
            color: #777;
            margin: 0 0 30px;
        }

        strong
        {
            display: block;
            padding: 10px 20px;
            background: #efefef;
            text-transform: capitalize;
        }

        pre
        {
            font-family: 'Courier', sans-serif;
        }

        p,
        pre
        {
            margin: 0 0 20px;
            background: #fee;
            padding: 20px;
            color: #555;
            word-break: break-all;
        }
    </style>
</head>
<body>
<div id="content">
    <div style="text-align: center">
        <h1>
            <span><?php echo $errorContext->getHttpStatusCode() ?></span>
        </h1>

        <h2>
            <?php echo $errorContext->getMessage() ?>
        </h2>

        <div id="date">Date/Time: <?php echo (new DateTime())->format('c') ?></div>
    </div>
</div>
</body>
</html>