<?php
/**
 * @var FlashMessage $flash
 * @var Locale $locale
 *
 * @var string $activeTabId
 * @var array $tabs
 * @var string $content
 */
use Simplon\Locale\Locale;
use Simplon\Mvc\Utils\CastAway;
use Simplon\Mvc\Views\Browser\FlashMessage;

$tabCount = count($tabs);
$tabItemClass = $tabCount > 1 ? CastAway::intToColumnWord($tabCount) . ' item' : null;
?>

<div class="nav-section-tabs ui top attached <?= $tabItemClass ?> tabular menu">
    <?php foreach ($tabs as $id => $tab): ?>
        <a href="<?= $tab['url'] ?>" class="item <?= $id === $activeTabId ? 'active' : null ?>">
            <?= $tab['label'] ?>
        </a>
    <?php endforeach ?>
</div>
<div class="nav-section-content ui bottom attached segment">
    <?= $content ?>
</div>