<?php
/**
 * @var FlashMessage $flash
 * @var Locale $trans
 *
 * @var string $cssVendor
 * @var string $cssPage
 * @var string $cssComponent
 * @var string $codeDefault
 * @var string $jsVendor
 * @var string $jsPage
 * @var string $jsComponent
 *
 * @var string $partialModule
 */
use Simplon\Locale\Locale;
use Simplon\Mvc\Views\Browser\FlashMessage;

?>
<!DOCTYPE html>
<html lang="<?= $trans->getCurrentLocale() ?>">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0">
    <title><?= $trans->get('page-title') ?></title>
    <link rel="shortcut icon" href="/favicon.ico" type="image/x-icon">
    <link rel="icon" href="/favicon.ico" type="image/x-icon">

    <?php foreach (['cssVendor', 'cssPage', 'cssComponent'] as $block): ?>
        <?php if (isset($$block)): ?>
            <?= $$block ?>
        <?php endif ?>
    <?php endforeach ?>
</head>
<body>
<?= $partialModule ?>

<?php foreach (['codeDefault', 'jsVendor', 'jsPage', 'jsComponent'] as $block): ?>
    <?php if (isset($$block)): ?>
        <?= $$block ?>
    <?php endif ?>
<?php endforeach ?>
</body>
</html>